uc-cdis/indexclient

- README.md
This adds a first pass of the README.
> first pass readme

- bin/index
- index/parsers/find.py
Simplifies root parser structure and adds a new find function.
> Find function

- indexclient/client.py
- fixed Document.patch, Document.delete
- fixed Client.list
r? @rudyardrichter
> fix(patch): fix document.patch

- indexclient/client.py
- remove all the null fields as jsonschema doesn't allow that
- fix some broken code
> fix(client): fix create to match schema

- indexclient/client.py
- indexclient/parsers/create.py
- indexclient/parsers/delete.py
- indexclient/parsers/info.py
- indexclient/parsers/name.py
- indexclient/parsers/retrieve.py
- indexclient/parsers/search.py
- indexclient/parsers/update.py
- setup.py
add metadata field to request @philloooo @rudyardrichter
> feat(metadata): add metadata to request

- indexclient/client.py
- load all attributes received from server to current document instance. This relieves us from needing to update indexclient whenever we add new attributes on the server side
> feat(document): get all attributes

- indexclient/client.py
- let self._doc be a property fetched directly from `cls.__dict__`
- only patch allowed attributes
> feat(client): only patch allowed attrs

- .travis.yml
- indexclient/client.py
- test-requirements.txt
- tests/conftest.py
- tests/test_client.py
added first real test
depends on https://github.com/uc-cdis/cdisutils-test/pull/6
> feat(test): setup test

- indexclient/client.py
- test-requirements.txt
- tests/conftest.py
- tests/test_client.py
Added functions for:
* Getting the latest revision on an entry
* Adding a new revision to an entry
* Listing revisions for an entry
> feat(versioning): support for adding, listing, and retrieving revisions

- .github/CODEOWNERS
https://help.github.com/articles/about-codeowners/
not sure if it will work, have to merge then see...
> chore(git-owners): planx devs are owners

- indexclient/client.py
- setup.py
- test-requirements.txt
- tests/test_client.py
Set client version to 1.4.3
upgraded indexd server test version 0.5.0
add metadata to list of update-able fields
> feat(versioning): metadata to updatables

- indexclient/client.py
- tests/test_client.py
This addresses https://jira.opensciencedatacloud.org/browse/TT-543
> fix(list): allow listing more than 'page_size' docs

- indexclient/client.py
- test-requirements.txt
- tests/test_client.py
coupled with https://github.com/uc-cdis/sheepdog/pull/120
> feat(acl): allow acl create and update

- indexclient/client.py
- test-requirements.txt
- tests/test_client.py
> feat(urls_metadata): support urls_metadata

- indexclient/client.py
- test-requirements.txt
- tests/test_client.py
update `list` method to to get document directly from the list request instead of doing separate calls to fetch each id
this depends on https://github.com/uc-cdis/indexd/pull/127
> feat(list): get full record in list

- .gitignore
- indexclient/client.py
- test-requirements.txt
- tests/test_client.py
Implements https://github.com/uc-cdis/indexd/pull/154
> feat(bulk): add bulk requests in client

- indexclient/client.py
- tests/test_client.py
Implements https://github.com/uc-cdis/indexd/pull/150
> fix(patch): allow none attributes in doc patches

- indexclient/client.py
- Add ways to compare Documents with equals and not equals.
```
Document(None, None, json={}) == Document(None, None, json={})
Document(None, None, json={}) != Document(None, None, json={})
```
> feat(magic): add eq/ne magic methods to indexd

- indexclient/client.py
Description about what this pull request does.
Sometimes requests hang forever, we should add the timeout and retry logic so that if the server does not respond it will not block the client at least
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
Add timeout and retry logic
> feat(retry): add retry logic

- indexclient/client.py
- test-requirements.txt
- tests/test_client.py
- tests/test_document.py
This depends on uc-cdis/cdisutils-test#19 and latest IndexD server for testing.
- Support new RBAC field
> PXD-2847: support rbac field

- README.md
- indexclient/client.py
Update README and add uploader field to the create and update record functions.
> fix: update README and add uploader field to the create and update record functions

- .github/main.workflow
- .github/workflows/wool.yml
the old workflow format was deprecated in september
> fix(wool): update workflow

- indexclient/client.py
- Do not crash if the response from indexd does not contain JSON
> fix(jsonerror)

- Pipfile
- Pipfile.lock
- indexclient/client.py
- tests/test_client.py
Jira Ticket: [PXP-6421](https://ctds-planx.atlassian.net/browse/PXP-6421)
- Fixes description not updating.
[PXP-6421]: https://ctds-planx.atlassian.net/browse/PXP-6421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug(PXP-6421): Fix description not updating

- .gitignore
- .travis.yml
- Pipfile
- Pipfile.lock
- indexclient/client.py
- Adds description, content_updated_time and content_created_time fields for index records.
- Updates indexd to 5.0.1 from 3.5.0
> feat(DCF-1385) Adds description and content dates
